include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"
cspell:
  stage: validate
  image: node:18
  before_script:
    - npm install -g cspell
  script:
    - cspell "**/*.{php,module,inc,install,test,profile,theme,js,css,md,yml,txt}" --no-progress || true
  allow_failure: true

eslint:
  stage: validate
  image: node:18
  before_script:
    - corepack enable
    - yarn install
  script:
    - yarn lint:js || true
    - yarn lint:yaml || true
  after_script:
    - touch junit.xml _eslint.patch
  allow_failure: true

stylelint:
  stage: validate
  image: node:18
  before_script:
    - corepack enable
    - yarn install
  script:
    - yarn lint:css || true
  after_script:
    - echo '[]' > gl-codequality.json
  allow_failure: true
