name: Web Releases - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - path
  - pathauto
  - text
  - link
  - image
  - node
  - user
  - views
  - menu_ui
  - menu_link_content
  - content_moderation
  - field_layout
  - media
  - media_library
  - layout_builder
  - layout_discovery
  - manage_display
  - webpage
config:
  strict: false
  import:
    webpage: '*'
